runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: out
  secure: always
  # Use 0 for local development. deploy.py changes this to 365d with perma-urls
  expiration: "0"
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always
  # Use 0 for local development. deploy.py changes this to 365d with perma-urls
  expiration: "0"
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  secure: always
  expiration: "28d"
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: '*'

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
  http_headers:
    Access-Control-Allow-Origin: '*'
